using Mediator;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using SalahBahazad.Application.Common.Exceptions;
using SalahBahazad.Application.Common.Interfaces;
using SalahBahazad.Application.Features.Codes.DTOs;
using SalahBahazad.Domain.Entities;

namespace SalahBahazad.Application.Features.Codes.Commands.GenerateCodeBatch;

internal sealed class GenerateCodeBatchHandler(
    IAppDbContext db,
    ICurrentUserResolver currentUser,
    TimeProvider clock,
    ILogger<GenerateCodeBatchHandler> logger)
    : IRequestHandler<GenerateCodeBatchCommand, CodeBatchDto>
{
    public async ValueTask<CodeBatchDto> Handle(GenerateCodeBatchCommand command, CancellationToken cancellationToken)
    {
        // The target session must exist in the caller's tenant (query filter applies).
        var session = await db.Sessions
            .FirstOrDefaultAsync(s => s.Id == command.SessionId, cancellationToken)
            ?? throw new NotFoundException("Session", command.SessionId);

        // Default the face value to the session's current price (contract §5).
        var value = command.Value ?? session.Price;
        var now = clock.GetUtcNow();
        var label = await GenerateLabelAsync(now, cancellationToken);

        // Seed the generator with the tenant's existing serials (incl. soft-deleted) so new ones never collide.
        var existingSerials = await db.Codes
            .IgnoreQueryFilters()
            .Where(c => c.TenantId == currentUser.TenantId)
            .Select(c => c.Serial)
            .ToHashSetAsync(cancellationToken);

        var batch = CodeBatch.Generate(
            currentUser.TenantId, session.Id, value, command.Quantity, label, existingSerials);

        db.CodeBatches.Add(batch); // cascades the minted codes
        await db.SaveChangesAsync(cancellationToken);

        logger.LogInformation(
            "Code batch {BatchId} ({Quantity} codes) generated by {ActorId}",
            batch.Id, batch.Quantity, currentUser.UserId);

        return batch.ToBatchDto(session.Title);
    }

    /// <summary>Server-generated readable label, sequenced per tenant per day, e.g. <c>CODES-20260620-01</c>.</summary>
    private async Task<string> GenerateLabelAsync(DateTimeOffset now, CancellationToken cancellationToken)
    {
        var dayStart = new DateTimeOffset(now.UtcDateTime.Date, TimeSpan.Zero);
        var dayEnd = dayStart.AddDays(1);
        var todayCount = await db.CodeBatches
            .CountAsync(b => b.CreatedAtUtc >= dayStart && b.CreatedAtUtc < dayEnd, cancellationToken);
        return $"CODES-{now:yyyyMMdd}-{todayCount + 1:D2}";
    }
}
